apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: F:\Etudes\Futur\ESGI\Projets\Perso\docker\kubernetes\bin\kompose.exe
      convert
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 80
  - name: "5858"
    port: 5858
    targetPort: 5858
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
